# NSE and BSE trading hours (IST)
MARKET_OPEN_TIME = "09:15:00"
MARKET_CLOSE_TIME = "15:30:00"

# Instrument types
INSTRUMENT_EQUITY = "EQ"
INSTRUMENT_FUTURES = "FUT"
INSTRUMENT_OPTIONS = "OPT"

# Order types
ORDER_TYPE_MARKET = "MARKET"
ORDER_TYPE_LIMIT = "LIMIT"
ORDER_TYPE_SL = "SL"
ORDER_TYPE_SL_M = "SL-M"

# Products
PRODUCT_MIS = "MIS"
PRODUCT_CNC = "CNC"
PRODUCT_NRML = "NRML"

# Transaction types
TRANSACTION_TYPE_BUY = "BUY"
TRANSACTION_TYPE_SELL = "SELL"

# Exchanges
EXCHANGE_NSE = "NSE"
EXCHANGE_BSE = "BSE"
EXCHANGE_NFO = "NFO"
EXCHANGE_CDS = "CDS"
EXCHANGE_MCX = "MCX"

# Default symbols for market watch
DEFAULT_EQUITY_SYMBOLS = [
    'RELIANCE', 'TCS', 'HDFC', 'INFY', 'HINDUNILVR', 
    'SBIN', 'BHARTIARTL', 'ITC', 'KOTAKBANK', 'ICICIBANK',
    'LT', 'AXISBANK', 'ASIANPAINT', 'MARUTI', 'SUNPHARMA',
    'TITAN', 'ULTRACEMCO', 'WIPRO', 'NESTLEIND', 'HCLTECH'
]

DEFAULT_FNO_SYMBOLS = [
    'NIFTY', 'BANKNIFTY', 'RELIANCE', 'TCS', 'INFY',
    'HDFC', 'SBIN', 'ICICIBANK', 'AXISBANK', 'KOTAKBANK'
]

# Risk management parameters
MAX_POSITION_SIZE = 100000  # ₹1 Lakh per position
DAILY_LOSS_LIMIT = 5000     # ₹5000 daily loss limit
MAX_OPEN_POSITIONS = 5